name: Extract Token and Nuclei Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  rbac-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM application
        run: npm install

      - name: Start NPM application
        run: nohup npm start > /dev/null 2>&1 &

      - name: Wait for NPM server to be ready
        run: |
          until curl --output /dev/null -s --head http://127.0.0.1:3000; do
            sleep 1
          done

      - name: Extract JWTs
        run: |
          response_user=$(curl -s http://localhost:3000/api/login --data '{"username":"user1", "password":"password"}' -H "Content-Type: application/json")
          token_user=$(echo "$response_user" | grep -oE '"token":"[^"]+' | cut -d':' -f2 | tr -d '"')
          echo "TOKEN_USER=$token_user" >> $GITHUB_ENV
          
          response_admin=$(curl -s http://localhost:3000/api/login --data '{"username":"admin1", "password":"password"}' -H "Content-Type: application/json")
          token_admin=$(echo "$response_admin" | grep -oE '"token":"[^"]+' | cut -d':' -f2 | tr -d '"')
          echo "TOKEN_ADMIN=$token_admin" >> $GITHUB_ENV

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Nuclei - RBAC Tests
        uses: projectdiscovery/nuclei-action@main
        with:
          target: http://127.0.0.1:3000
          templates: rbac_tests/templates
          flags: "-var token_user=$TOKEN_USER -var token_admin=$TOKEN_ADMIN -silent -severity high -je results.json"
          github-report: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: RBAC Test Results
          path: results.json

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r rbac_tests/matrix_generator/requirements.txt

      - name: Generate RBAC Matrix Markdown
        run: python rbac_tests/matrix_generator/main.py -t rbac_tests/templates -r results.json -om docs/permissions/MATRIX.md

      - name: Commit Matrix
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/permissions/MATRIX.md
          git commit -m "Update permissions matrix"

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
